### ISSUE TITLE
npm scope support

### ISSUE THREAD

**Issue by destroyerofbuilds** [yleo77/grunt-task-loader#2]
The `grunt-task-loader` module does not support scoped grunt plugins. [npm-scope](https://docs.npmjs.com/misc/scope).

Please see similar issues for [load-grunt-tasks](https://github.com/sindresorhus/load-grunt-tasks/issues/30) and [gulp-load-plugins](https://github.com/jackfranklin/gulp-load-plugins/issues/59).

**Comment by yleo77** [comment]
@destroyerofbuilds thx for your advice.
